python_test/conteudo/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.FilmeListView.as_view(), name='index'),
    url(r'^filme/(?P<slug>[-\w]+)/$', views.FilmeDetailView.as_view(), name='filme'),
    url(r'^ator/(?P<slug>[-\w]+)/$', views.AtorDetailView.as_view(), name='ator'),
    url(r'^genero/(?P<slug>[-\w]+)/$', views.FilmeListView.as_view(), name='genero'),
]

python_test/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'', include('python_test.conteudo.urls', namespace='conteudo')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python_test/conteudo/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse

from autoslug import AutoSlugField


class Ator(models.Model):
    nome = models.CharField(verbose_name='Nome', max_length=50)
    slug = AutoSlugField(verbose_name='Slug', populate_from='nome')

    pais = models.CharField(verbose_name='País de Origem', max_length=30)
    foto = models.ImageField(verbose_name='Foto', upload_to='atores/')

    def __unicode__(self):
        return '{}'.format(self.nome)

    @staticmethod
    def autocomplete_search_fields():
        return ('id__iexact', 'nome__icontains')

    def get_absolute_url(self):
        return reverse('conteudo:ator', args=(self.slug,))

    class Meta:
        verbose_name = 'Ator'
        verbose_name_plural = 'Atores'
        ordering = ('nome',)


class Filme(models.Model):
    nome = models.CharField(verbose_name='Nome', max_length=50)
    slug = AutoSlugField(verbose_name='Slug', populate_from='nome')

    sinopse = models.TextField(verbose_name='Sinopse')
    cartaz = models.ImageField(verbose_name='Cartaz', upload_to='cartazes/')

    atores = models.ManyToManyField('Ator')
    generos = models.ManyToManyField('Genero')

    def __unicode__(self):
        return '{}'.format(self.nome)

    @staticmethod
    def autocomplete_search_fields():
        return ('id__iexact', 'nome__icontains')

    def get_absolute_url(self):
        return reverse('conteudo:filme', args=(self.slug,))

    class Meta:
        verbose_name = 'Filme'
        verbose_name_plural = 'Filmes'
        ordering = ('nome',)


class Genero(models.Model):
    nome = models.CharField(verbose_name='Nome', max_length=50)
    slug = AutoSlugField(verbose_name='Slug', populate_from='nome')

    def __unicode__(self):
        return '{}'.format(self.nome)

    @staticmethod
    def autocomplete_search_fields():
        return ('id__iexact', 'nome__icontains')

    def get_absolute_url(self):
        return reverse('conteudo:genero', args=(self.slug,))

    class Meta:
        verbose_name = 'Genero'
        verbose_name_plural = 'Generos'
        ordering = ('nome',)

python_test/conteudo/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db.models import Count, Q
from django.views import generic

from .models import Ator, Genero, Filme


class AtorDetailView(generic.DetailView):
    model = Ator


class FilmeDetailView(generic.DetailView):
    model = Filme

    def get_queryset(self):
        return (
            super(FilmeDetailView, self).get_queryset()
            .prefetch_related('generos')
            .prefetch_related('atores')
        )

    def get_filmes_relacionados(self):
        return (
            self.model.objects
            .exclude(pk=self.object.pk)
            .filter(
                Q(atores__in=self.object.atores.all()) |
                Q(generos__in=self.object.generos.all())
            )
            .annotate(peso=Count('pk'))
            .order_by('-peso')
        )[:10]

    def get_context_data(self, **kwargs):
        context = super(FilmeDetailView, self).get_context_data(**kwargs)
        context.update({
            'filmes_relacionados': self.get_filmes_relacionados()
        })

        return context


class FilmeListView(generic.ListView):
    model = Filme

    def get(self, request, *args, **kwargs):
        self.genero = None
        slug = self.kwargs.get('slug')

        if slug:
            self.genero = Genero.objects.get(slug=slug)

        return super(FilmeListView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        qs = super(FilmeListView, self).get_queryset()

        ordem = self.request.GET.get('ordem')
        if ordem and ordem == 'desc':
            qs = qs.order_by('-nome')

        if self.genero:
            qs = qs.filter(generos=self.genero)

        return qs

    def get_context_data(self, **kwargs):
        context = super(FilmeListView, self).get_context_data(**kwargs)
        context.update({
            'genero': self.genero,
        })

        return context

python_test/conteudo/templates/conteudo/_lista.html
{% load imagekit %}

<ul>
  {% for filme in object_list %}
    <li class="fl {% if forloop.counter|divisibleby:5 %}last{% endif %} ">
      <a href="{{ filme.get_absolute_url }}">
        {% thumbnail '168x216' filme.cartaz -- alt=filme.nome title=filme.nome %}
      </a>
    </li>
  {% endfor %}
</ul>

python_test/conteudo/templates/conteudo/ator_detail.html
{% extends 'conteudo/base.html' %}

{% load cache %}
{% load imagekit %}

{% block title %}
  {{ object.nome }}
{% endblock %}

{% block main %}
<header class="fix">
  <h1>Atores</h1>
</header>

<section id="Infos" class='fix'>
  <figure class="fl">
    {% thumbnail '160x100' object.foto -- alt=object.nome title=object.nome %}
  </figure>

  <article class="fl">
    <p class="tit">Ator</p>
    <h2>{{ object.nome }}</h2>
    <p class="txt"><strong>País:</strong> {{ object.pais }}</p>

  </article>

</section>

<section id="listagem" class='fix'>
  <header class="fix">
    <h2>Filmes Relacionados</h2>
  </header>
  <ul>
    {% cache 3600 filmes_relacionados_ator object.pk %}
      {% with object_list=object.filme_set.all|slice:':20' %}
        {% include 'conteudo/_lista.html' %}
      {% endwith %}
    {% endcache %}
  </ul>
</section>
{% endblock %}

python_test/conteudo/templates/conteudo/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>

  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/comum.css' %}">
</head>
<body>
  <header id="header">
    <div class="content">
      <a href="{% url 'conteudo:index' %}" class="home" title="voltar para home"></a>
    </div>
  </header>
  <main id="Content" class="fix">
    {% block main %}{% endblock %}
  </main>
</body>
</html>

python_test/conteudo/templates/conteudo/filme_detail.html
{% extends 'conteudo/base.html' %}

{% load cache %}
{% load imagekit %}
{% load pretty_join %}

{% block title %}
  {{ object.nome }}
{% endblock %}

{% block main %}
<header class="fix">
  <h1>{{ object.nome }}</h1>
</header>

<section id="Infos" class='fix'>
  <figure class="fl">
    {% thumbnail '220x283' object.cartaz -- alt=object.nome title=object.nome %}
  </figure>

  <article class="fl">
    <p class="tit">Sinopse:</p>
    <p class="txt">{{ object.sinopse }}</p>
    <p class="tit">Genero:</p>
    <p class="txt">{{ object.generos.all|pretty_join }}.</p>

    <p class="tit">Atores:</p>
    <p class="txt">{{ object.atores.all|pretty_join }}.</p>
  </article>

</section>

<section id="listagem" class='fix'>
  <header class="fix">
    <h2>Filmes Relacionados</h2>
  </header>
  {% cache 3600 filmes_relacionados_filme object.pk %}
    {% with object_list=filmes_relacionados %}
      {% include 'conteudo/_lista.html' %}
    {% endwith %}
  {% endcache %}
</section>
{% endblock %}

python_test/conteudo/templates/conteudo/filme_list.html
{% extends 'conteudo/base.html' %}

{% block title %}
  {% if genero %}
    {{ genero.nome }}
  {% else %}
    Listagem de Filmes
  {% endif %}
{% endblock %}

{% block main %}
<header class="fix">
  <h1 class="fl">
    {% if genero %}
      {{ genero.nome }}
    {% else %}
      Listagem de Filmes
    {% endif %}
  </h1>
  <form action="">
    <select name="ordem" onchange="javascript:this.form.submit()" class="fr">
      <option value="">Ordenar por:</option>
      <option value="asc">a - z</option>
      <option value="desc">z - a</option>
    </select>
  </form>
</header>

<section id="listagem" class='fix'>
  {% include 'conteudo/_lista.html' %}
</section>
{% endblock %}